# Config commune a tous les profils
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health

# Profil actif par defaut (peut etre surcharge par variable d'environnement)
spring.profiles.active=local