# PROFIL PROD : OpenShift, tout vient des variables d'environnement
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false
management.endpoints.web.exposure.include=health