# PROFIL LOCAL : ta machine avec PostgreSQL local (port 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/conges
spring.datasource.username=conges
spring.datasource.password=conges
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health